rules:
  secrets-outside-env:
    ignore:
      - ec-checker.yml:56:34
      - ec-checker.yml:59:24
      - php-coding-standard.yml:63:30
      - php-coding-standard.yml:122:30
      - php-coding-standard.yml:134:34
      - php-coding-standard.yml:137:24
      - php-coding-standard.yml:182:30
      - php-coding-standard.yml:194:34
      - php-coding-standard.yml:197:24
      - php-validate-composer.yml:107:30
      - php-validate-composer.yml:112:34
      - php-validate-composer.yml:115:24
      - phpstan.yml:61:30
      - phpstan.yml:69:34
      - phpstan.yml:72:24
      - phpunit.yml:85:30
      - phpunit.yml:105:34
      - phpunit.yml:108:24
      - sqlfluff.yml:53:30
      - sqlfluff.yml:72:34
      - sqlfluff.yml:75:24
