# SPDX-FileCopyrightText: Copyright 2026 Framna Netherlands B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: SQLFluff
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      identifier:
        required: false
        type: string
        default: 'SQL Files'
      dialect:
        required: false
        type: string
        default: 'mariadb'
      required:
        type: boolean
        default: false
    secrets:
      COMPOSER_AUTH:
        required: false
      SLACK_WEBHOOK_URL:
        required: false

env:
  SLACK_SEND_EVENTS: '["push", "schedule"]'

jobs:
  sqlfluff:
    runs-on: ubuntu-latest
    continue-on-error: ${{ !inputs.required }}
    name: "SQLFluff (${{ inputs.identifier }})"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: "latest"

      - name: Install dependencies
        run: composer install
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Lint SQL
        env:
          FILES_PATH: ${{ inputs.path }}
          DIALECT: ${{ inputs.dialect }}
        run: composer run-script sqlfluff "$FILES_PATH" "$DIALECT"

      - name: Post a message in a channel
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() && contains(fromJSON(env.SLACK_SEND_EVENTS), github.event_name) && env.SLACK_WEBHOOK_URL != '' }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*${{ github.repository }} (${{ github.ref_name }})*: SQLFluff (${{ inputs.identifier }}) ${{ job.status }}\nURL: ${{ github.event.pull_request.html_url || format('https://github.com/{0}/commit/{1}', github.repository, github.sha) }}\nWorkflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*${{ github.repository }} (${{ github.ref_name }})*: SQLFluff (${{ inputs.identifier }}) ${{ job.status }}\nURL: ${{ github.event.pull_request.html_url || format('https://github.com/{0}/commit/{1}', github.repository, github.sha) }}\nWorkflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
