# SPDX-FileCopyrightText: Copyright 2023 Move Agency Group B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: Spellcheck
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: 'typos.toml'

jobs:
  typos:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: "Spellcheck (typos)"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d # v1.44.0
        with:
          config: ${{ inputs.config }}
