# SPDX-FileCopyrightText: Copyright 2023 Move Agency Group B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: Spellcheck
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: 'typos.toml'

jobs:
  typos:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: "Spellcheck (typos)"
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@37bb98842b0d8c4ffebdb75301a13db0267cef89 # v1.47.2
        with:
          config: ${{ inputs.config }}
